name: Package Background Library

on:
  push:
    paths:
      - ".github/workflows/package_backgrounds.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ZIP
        run: zip -r AVELEA_BACKGROUNDS.zip BACKGROUNDS

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: AVELEA_BACKGROUNDS
          path: AVELEA_BACKGROUNDS.zip
          retention-days: 7
